### ISSUE TITLE
為啥有那麼多的壓縮包？

### ISSUE THREAD

**Issue by solome** [annethf/Marginalia#2]
如題，為啥有那麼多壓縮包？

> 為什麼要壓縮源代碼呢，還用數字區分版本？git就是用來進行版本控制的呀...
> 建議多找些資料了解下git的用途 & 使用技巧！
#### 參考
- [#git-scm](http://git-scm.com)

**Comment by annethf** [comment]
我不知道哎，所以就每写一个就传一个…又丢人了…

发自我的 iPhone

**Comment by annethf** [comment]
我不知道哎，所以就写一个传一个…又丢人了…
发自我的 iPhone

**Comment by solome** [comment]
麼有動靜了，最近兩日...

**Comment by annethf** [comment]
看论文呢，DAC 没搞清楚，理论和代码执行结果不一致，不知道是理论理解错了，还是代码写错了…

发自我的 iPhone

**Comment by annethf** [comment]
看论文呢，dac搞不清楚…
发自我的 iPhone

**Comment by annethf** [comment]
是像BinaryTree那样提交吗？
